In [1]:
import numpy as np

In [2]:
a =  np.array([1,2,3,4,5])

In [4]:
print(a)

[1 2 3 4 5]


In [5]:
a[0]

1

In [6]:
a[1]

2

In [7]:
a[2]

3

In [8]:
import time
import sys

In [9]:
b = range(1000)
print(sys.getsizeof(5)*len(b))

28000


In [10]:
c = np.arange(1000)
print(c.size*c.itemsize)

8000


In [11]:
size = 100000
L1 = range(size)
L2 = range(size)
A1 = np.arange(size)
A2 = np.arange(size)

In [14]:
start = time.time()
result = [(x+y) for x,y in zip(L1,L2)]
result = [(x+y) for x,y in zip(L1,L2)]
# print(result)
print("Python list took: ",(time.time()-start)*1000)

Python list took:  41.2142276763916


In [13]:
start = time.time()
result = A1+A2
print("Python array took: ",(time.time()-start)*1000)

Python array took:  4.185914993286133


In [16]:
a = np.array([[1,2],[3,4],[6,7]])
print(a)


[[1 2]
 [3 4]
 [6 7]]


In [18]:
a.ndim

2

In [19]:
a.itemsize

8

In [20]:
a.shape

(3, 2)

In [24]:
a = np.array([[1,2],[3,4],[5,6]] , dtype = np.float64)
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [27]:
a.itemsize

8

In [28]:
a.shape

(3, 2)

In [29]:
a.ndim

2

In [30]:
a = np.array([[1,2],[3,4],[5,6]] , dtype = np.complex)
a

/var/folders/hl/llrbs5vs0dzg_dcw7n59yd4r0000gn/T/ipykernel_5402/4003438190.py:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.array([[1,2],[3,4],[5,6]] , dtype = np.complex)


array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [31]:
arr = np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])
np.bincount(arr)

array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1])

In [32]:
a = np.zeros((1,0))

a.size

0

In [33]:
len(a)

1

In [38]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a == 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[False False False]
 [False False False]
 [False False False]]


In [39]:
from sketchpy import library as lib
obj = lib.rdj()
obj.draw()

ModuleNotFoundError: No module named 'sketchpy'