In [1]:
import numpy as np

Q1.) Get all 2D diagonals of a 3D NumPy array


In [9]:
arr_3D = np.arange(3 * 4 * 4).reshape(3, 4, 4)
arr = np.diagonal(arr_3D, axis1 = 1,axis2 = 2)
print(arr_3D)
print("2D array:")
print(arr)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]
2D array:
[[ 0  5 10 15]
 [16 21 26 31]
 [32 37 42 47]]


Q2) Calculate the mean across dimension in a 2D NumPy array

Input:
     [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
     
Output:

     Mean of Row 1 is 2.0
     Mean of Row 2 is 5.0
     Mean of Row 3 is 8.0
     Mean of column 1 is 4.0
     Mean of column 2 is 5.0
     Mean of column 3 is 6.0

In [34]:
arr = np.arange(1,10).reshape(3,3)

row_mean = np.mean(arr, axis=1)
  
row1_mean = row_mean[0]
print("Mean of Row 1 is", row1_mean)
  
row2_mean = row_mean[1]
print("Mean of Row 2 is", row2_mean)
  
row3_mean = row_mean[2]
print("Mean of Row 3 is", row3_mean)
  
column_mean = np.mean(arr, axis=0)
  
column1_mean = column_mean[0]
print("Mean of column 1 is", column1_mean)
  
column2_mean = column_mean[1]
print("Mean of column 2 is", column2_mean)
  
column3_mean = column_mean[2]
print("Mean of column 3 is", column3_mean)

Mean of Row 1 is 2.0
Mean of Row 2 is 5.0
Mean of Row 3 is 8.0
Mean of column 1 is 4.0
Mean of column 2 is 5.0
Mean of column 3 is 6.0


Q3)Construct a DataFrame in Pandas using string data

Input:

“””Date;Event;Cost
10/2/2011;Music;10000
11/2/2011;Poetry;12000
12/2/2011;Theatre;5000
13/2/2011;Comedy;8000
“””

In [35]:
import pandas as pd

In [39]:
dict = {"Date":["10/2/2011","11/2/2011","12/2/2011","13/2/2011"],"Event":["Music","Poetry","Theatre","Comedy"],"Cost":[10000,12000,5000,8000]}
df = pd.DataFrame(dict)
df

Date    Event   Cost
0  10/2/2011    Music  10000
1  11/2/2011   Poetry  12000
2  12/2/2011  Theatre   5000
3  13/2/2011   Comedy   8000

Q4) Provide different ways to iterate over rows in Pandas Dataframe

In [40]:
for i, j in df.iterrows():
    print(i, j)
    print()

0 Date     10/2/2011
Event        Music
Cost         10000
Name: 0, dtype: object

1 Date     11/2/2011
Event       Poetry
Cost         12000
Name: 1, dtype: object

2 Date     12/2/2011
Event      Theatre
Cost          5000
Name: 2, dtype: object

3 Date     13/2/2011
Event       Comedy
Cost          8000
Name: 3, dtype: object



In [41]:
for key, value in df.iteritems():
    print(key, value)
    print()

Date 0    10/2/2011
1    11/2/2011
2    12/2/2011
3    13/2/2011
Name: Date, dtype: object

Event 0      Music
1     Poetry
2    Theatre
3     Comedy
Name: Event, dtype: object

Cost 0    10000
1    12000
2     5000
3     8000
Name: Cost, dtype: int64



In [43]:
for i in df.itertuples():
    print(i)

Pandas(Index=0, Date='10/2/2011', Event='Music', Cost=10000)
Pandas(Index=1, Date='11/2/2011', Event='Poetry', Cost=12000)
Pandas(Index=2, Date='12/2/2011', Event='Theatre', Cost=5000)
Pandas(Index=3, Date='13/2/2011', Event='Comedy', Cost=8000)


Q5) Write Python Program to Find closest number in array

Input : arr[] = {1, 2, 4, 5, 6, 6, 8, 9}
Target number = 11
Output : 9

9 is closest to 11 in given array

Input :arr[] = {2, 5, 6, 7, 8, 8, 9};
Target number = 4
Output : 5

In [58]:
l = []
n = int(input("Enter the size of array"))
for i in range (n):
    a = int(input())
    l.append(a)

arr = np.array(l)

target = int(input("Enter The target Element: "))

def findElement(arr , target):
    if target in arr:
        return target
    else:
        if(arr[n-1] < target):
            return arr[n-1]
        elif ( arr[0] > target):
            return arr[0]
        else:
            for i in range(1,n):
                if(arr[i]>target):
                    return arr[i]
    

print(findElement(arr,target))        

Enter the size of array7
2
5
6
7
8
8
9
Enter The target Element: 4
5
