In [2]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [7]:
%timeit [j**4 for j in range(1,9)]

3.01 µs ± 6.56 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
%timeit np.arange(1,9)**4 

1.91 µs ± 3.26 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [13]:
l =[] 
for i in range(5):
    l.append(int(input()))
    
b = np.array(l)
print(b)
    

1
2
3
4
5
[1 2 3 4 5]


In [14]:
type(b)

numpy.ndarray

In [16]:
np.ndim(b)

1

In [18]:
array = np.array([1,2,3,4],ndmin = 10)
array

array([[[[[[[[[[1, 2, 3, 4]]]]]]]]]])

### Zeors

In [22]:
ar_zero = np.zeros(4)
ar_zero

array([0., 0., 0., 0.])

In [26]:
zero1 = np.zeros((3,4))
print(zero1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones

In [29]:
ar_ones = np.ones(3)
print(ar_ones)

[1. 1. 1.]


In [30]:
ar_ones1 = np.ones((3,4))
print(ar_ones1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [8]:
ar_empty = np.empty(4)
print(ar_empty)

[0. 0. 0. 0.]


In [14]:
for i in np.nditer(ar_empty):
    print(i ,end = " ")

0.0 0.0 0.0 0.0 

# RANGE

In [32]:
ar_range = np.arange(1,8)
print(ar_range)

[1 2 3 4 5 6 7]


# Diagonal

In [33]:
ar_diagonal = np.eye(3)
print(ar_diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Linspace

In [36]:
ar_lin = np.linspace(1,10,num=100)
print(ar_lin)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

# Reshape

In [41]:
arr = np.arange(1,9)
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [106]:
x = arr.reshape(2,4)
print(x)
print(np.ndim(x))

[[1 2 3 4]
 [5 6 7 8]]
2


In [107]:
y = x.reshape(2,2,2)
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [108]:
one = y.reshape(-1)
print(one)
print(one.ndim)

[1 2 3 4 5 6 7 8]
1


In [109]:
one_1 = x.flatten()
print(one_1)

[1 2 3 4 5 6 7 8]


In [113]:
one_2 = x.ravel()
print(one_2)
a =list(one_2)
print(a)

[1 2 3 4 5 6 7 8]
[1, 2, 3, 4, 5, 6, 7, 8]


# Random

## Rand()
Function is use to generate a random value between 0 and 1

In [55]:
a = np.random.rand(4)
print(a)

[0.16269143 0.46255577 0.51601261 0.34149331]


## Randn()
Function is to generate a random value close to zero. This may be return postive or negative value as well.

In [66]:
b = np.random.randn(5)
b

array([-1.72203955, -0.5792908 ,  0.53950009, -0.12826653,  0.41052996])

## Ranf()
Function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open intervals [0.0,1.0)

In [67]:
c = np.random.ranf(5)
print(c)

[0.55331174 0.18038567 0.13360794 0.62032648 0.96807861]


## Randint()
Function is uesd to generate a random number between a given range.

In [71]:
d = np.random.randint(1,4,10)
print(d)

[3 3 3 1 3 1 1 3 3 3]


# DATATYPE

In [75]:
print("Data type: ",a.dtype)

Data type:  float64


In [77]:
e = np.array(["S","A","D","G","I"])
print(e.dtype)

<U1


In [78]:
f = np.array(["S","A","D","G","I",2,1,0,"B","T","C","S","E","A","M",0,2,0])
print(f.dtype)

<U21


In [84]:
#to convert one data into another
x = np.array([1,2,3,4], dtype = "f")
print(x.dtype)
print(x)

float32
[1. 2. 3. 4.]


In [87]:
# to change the datatype
y = np.array([1,2,3,4], dtype = np.int8)
print(y.dtype)
print(y)

int8
[1 2 3 4]


## Changing datatype as a function

In [91]:
y1 = np.array([1,2,3,4])

new = np.float32(y1)

print(y1.dtype)
print(y1)
print()
print(new)
print(new.dtype)

int64
[1 2 3 4]

[1. 2. 3. 4.]
float32


## astype()

In [97]:
x3 = np.array([1,2,3,4])
new_1 = x3.astype(float)
print(x3)
print(new_1)
print()
print(x3.dtype)
print(new_1.dtype)

[1 2 3 4]
[1. 2. 3. 4.]

int64
float64


# Arithmetic Operation

In [114]:
a = np.array([1,2,3,4])

add = a+3
print(add)

[4 5 6 7]


In [115]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
add_1 = a+b
print(add_1)

[2 4 6 8]


In [116]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
sub_1 = a-b
print(sub_1)

[0 0 0 0]


In [117]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
mul_1 = a*b
print(mul_1)

[ 1  4  9 16]


In [118]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
div_1 = a/b
print(div_1)

[1. 1. 1. 1.]


In [121]:
a = np.array([1,2,13,4])
b = np.array([1,2,4,4])
mod_1 = a%b
print(mod_1)

[0 0 1 0]


In [130]:
print("Minimum: ",np.min(a))
print("Postion of min value: ",np.argmin(a)) #position of min value
print()
print("Maximum: ",np.max(a))
print("Postion of max value: ",np.argmax(a)) #position of max value

Minimum:  1
Postion of min value:  0

Maximum:  13
Postion of max value:  2


In [128]:
print(np.sqrt(a))
print()
print(np.sin(a))

0

[1.         1.41421356 3.60555128 2.        ]

[ 0.84147098  0.90929743  0.42016704 -0.7568025 ]


In [142]:
var1 = np.array([[2,1,3],[9,5,6]])
print("Row-wise")
print()
print("Maximum: ",np.max(var1,axis =1 ))
print("Postion of max value: ",np.argmax(var1 ,axis =1))
print()
print("Maximum: ",np.min(var1,axis =1 ))
print("Postion of min value: ",np.argmin(var1 ,axis =1))
print()
print("Columnwise")
print()
print("Maximum: ",np.max(var1,axis =0 ))
print("Postion of max value: ",np.argmax(var1 ,axis =0))
print()
print("Maximum: ",np.min(var1,axis =0))
print("Postion of max value: ",np.argmin(var1 ,axis =0))


Row-wise

Maximum:  [3 9]
Postion of max value:  [2 0]

Maximum:  [1 5]
Postion of min value:  [1 1]

Columnwise

Maximum:  [9 5 6]
Postion of max value:  [1 1 1]

Maximum:  [2 1 3]
Postion of max value:  [0 0 0]


In [143]:
print(np.cumsum(var1))

[ 2  3  6 15 20 26]


# Broadcasting error


# indexing


In [144]:
var = np.array([9,8,7,6])
print(var[0],var[-1])

9 6


In [149]:
var_2 = np.array([[9,8,7,4],[0,1,3,4]])
print(var_2[0][-1])
print(var_2[1][-2])

4
3


In [152]:
var_3 = np.array([[[1,2,3],[3,4,5]],[[1,3,2],[0,3,1]]])
print(var_3[0][1][1])

4


# Slicing Numpy Arrays

In [153]:
var = np.array([1,2,3,4,5,6,7])
print(var)
print()
print(var[1:5])

[1 2 3 4 5 6 7]

[2 3 4 5]


In [156]:
print(var[:5:2])

[1 3 5]


In [157]:
var_2 = np.array([[9,8,7,4],[0,1,3,4]])
print(var_2[0,2:])

[7 4]


In [158]:
var_3 = np.array([[[1,2,3],[3,4,5]],[[1,3,2],[0,3,1]]])
print(var_3[0,1,1:])

[4 5]


# Iteration

In [12]:
var = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var:
    print(i,end =" ")

[9 8 7 6 5 4]

9 8 7 6 5 4 

In [167]:
var_1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var_1)
print()

for j in var_1:
    print(j,end=" ")
    
print()
print()

for k in var_1:
    for l in k:
        print(l,end = " ")

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4] [1 2 3 4] 

1 2 3 4 1 2 3 4 

In [13]:
var_3 = np.array([[[1,2,3,4],[5,6,7,8]]])
print(var_3)
print(var_3.shape)
print()

for i in var_3:
    for j in i:
        for k in j :
            print(k, end= " ")

[[[1 2 3 4]
  [5 6 7 8]]]
(1, 2, 4)

1 2 3 4 5 6 7 8 

# nditer()

In [16]:
for i in np.nditer(var_3):#,flags = ['buffered'],op_dtypes = ["S"]
    print(i,end=" ")

1 2 3 4 5 6 7 8 

In [7]:
for i,d in np.ndenumerate(var_3):
    print(i,d)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 1, 3) 8


# Copy Vs View

In [188]:
var = np.array([1,2,3,4])

co = var.copy()

var[2] = 0

print(var)
print(co)

[1 2 0 4]
[1 2 3 4]


In [186]:
x = np.array([9,8,7,6,5])

vi = x.view()

x[2] = 4

print(x)
print(vi)

[9 8 4 6 5]
[9 8 4 6 5]


# Join and Split Function

In [194]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])

a3 = np.concatenate((a1,a2))
print(a3)

[1 2 3 4 5 6 7 8]


In [199]:
b1 = np.array([[1,2,3,4],[0,0,0,0]])
b2 = np.array([[5,6,7,8],[0,0,0,0]])

b3 = np.concatenate((b1,b2),axis = 1)
print(b3)

print()

b4 = np.concatenate((b1,b2),axis = 0)
print(b4)

[[1 2 3 4 5 6 7 8]
 [0 0 0 0 0 0 0 0]]

[[1 2 3 4]
 [0 0 0 0]
 [5 6 7 8]
 [0 0 0 0]]


In [208]:
b1 = np.array([1,2,3,4])
b2 = np.array([5,6,7,8])

b3 = np.stack((b1,b2),axis = 1)
print(b3)

print()

b4 = np.stack((b1,b2),axis = 0)
print(b4)

print() 
b5 = np.hstack((b1,b2)) # row
print(b5)

print()

b6 = np.vstack((b1,b2))#columns
print(b6)

print() 

b7 = np.dstack((b1,b2))#height
print(b7)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]

[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


### Split

In [216]:
s1 = np.array([1,2,3,4,5,4,2,4,5])
print(s1)

ar = np.array_split(s1,4)
print() 
print(ar)


print()
print(ar[0])

[1 2 3 4 5 4 2 4 5]

[array([1, 2, 3]), array([4, 5]), array([4, 2]), array([4, 5])]

[1 2 3]


In [220]:
s2 = np.array([[1,2,3,4],[5,4,2,5]])
print(s2)

ar1 = np.array_split(s2,2)
print() 
print(ar1)


print()
print(ar1[0])

[[1 2 3 4]
 [5 4 2 5]]

[array([[1, 2, 3, 4]]), array([[5, 4, 2, 5]])]

[[1 2 3 4]]


In [223]:
# split along axis

ar2 = np.array_split(s2,4,axis =1)
print(ar2)

[array([[1],
       [5]]), array([[2],
       [4]]), array([[3],
       [2]]), array([[4],
       [5]])]


# Search

In [227]:
a = np.array([1,2,3,4,5,6,7,2,6,7])

b = np.where( a%2 == 0)

print(b)

(array([1, 3, 5, 7, 8]),)


# SEARCH SORTED ARRAY

In [233]:
a1 = np.array([1,2,3,4,5,6,7,7,9,10,11]) #ARRAY SHOULD BE SORTED
#              0,1,2,3,4,5,6,7

b1 = np.searchsorted( a1, [5,6,7] , side  = "right")

print(b1)
print(a1)

[5 6 8]
[ 1  2  3  4  5  6  7  7  9 10 11]


# Sort Array

In [240]:
c = np.array([4,2,31,12,5,6,7])

c =  np.sort(c)

print(c)

[ 2  4  5  6  7 12 31]


In [241]:
d = np.array(["a","A","s","d","D","G"])

d =  np.sort(d)

print(d)

['A' 'D' 'G' 'a' 'd' 's']


In [243]:
e = np.array([[4,2,31],[12,56,7]])
print(np.sort(e))

[[ 2  4 31]
 [ 7 12 56]]


# Filter Function

In [245]:
f = np.array(["a","s","d","f"])

f1 = [True,False,False,True]

f2 = f[f1]

print(f2)

['a' 'f']


# Shuffle()

In [251]:
S = np.array([1,2,3,4,5])

np.random.shuffle(S)

print(S)

[2 4 1 3 5]


# Unique()

In [256]:
U = np.array([1,2,3,4,1,2,3,1,2,3,1,2,3])

U1 = np.unique(U,return_index = True, return_counts = True)

print(U1)

(array([1, 2, 3, 4]), array([0, 1, 2, 3]), array([4, 4, 4, 1]))


# Resize()

In [259]:
R = np.array([1,2,3,4,5,6])

R1 = np.resize(R,(2,3))

print(R1)
print()

R2 = R.reshape(2,3)
print(R2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [260]:
R1 = np.resize(R,(3,2))

print(R1)

[[1 2]
 [3 4]
 [5 6]]



# Flatten()

In [264]:
R3 = R1.flatten(order = "A")

print(R3)

R3 = R1.flatten(order = "C")

print(R3)

R3 = R1.flatten(order = "F")

print(R3)

R3 = R1.flatten(order = "K")

print(R3)


[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 3 5 2 4 6]
[1 2 3 4 5 6]


# Ravel ()

In [267]:
print(np.ravel(R1, order = "A"))

[1 2 3 4 5 6]


# Insert and Delete

In [276]:
i = np.array([1,2,3,4,5,6,7,8])

print(i)
print(type(i))

i1 = np.insert(i , 8 , [9,10])

print(i1)

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10]


In [282]:
var1 = np.array([[1,2,3],[1,2,3]])

v1 = np.insert(var1 , 2 , 6,axis = 1)

print(v1)

print()

v1 = np.insert(var1 , 2 , 6,axis = 0)

print(v1)

[[1 2 6 3]
 [1 2 6 3]]

[[1 2 3]
 [1 2 3]
 [6 6 6]]


In [284]:
i = np.array([1,2,3,4,5,6,7,8])

print(i)
print(type(i))

i1 = np.append(i,6.5)

print(i1)

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
[1.  2.  3.  4.  5.  6.  7.  8.  6.5]


In [298]:
var2 = np.array([[1,2,3],[1,2,3]])

# v1 = np.append(var2,[[0,0]],axis = 1)

# print(v1)

print()

v1 = np.append(var2,[[0,0,0]],axis = 0)

print(v1)


[[1 2 3]
 [1 2 3]
 [0 0 0]]


In [299]:
d = np.array([1,2,3,4,5,6,7,8])

print(d)
print(type(d))

d1 = np.delete(d , 2 )

print(d1)

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
[1 2 4 5 6 7 8]


# Matrix in Numpy Array

In [301]:
var1 = np.matrix([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))

print()

arr =  np.array([[1,2,3],[1,2,3]])
print(arr)
print(type(arr))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [307]:
m1 = np.matrix([[1,2,3],[1,2,3]])
m2 = np.matrix([[1,2,3],[1,2,3]])
print(m1.dot(m2))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

# Matrix Function

# Transpose()

In [314]:
T = np.matrix([[1,2,3],[4,5,6]])

print(T)

print()

print(np.transpose(T))

print()

print(T.T)

[[1 2 3]
 [4 5 6]]

[[1 4]
 [2 5]
 [3 6]]

[[1 4]
 [2 5]
 [3 6]]


# Swapaxes()

In [317]:
S = np.matrix([[1,2,3],[4,5,6],[7,8,9]])

print(np.swapaxes(S, 0 ,1))

print()

print(np.swapaxes(S, 1 ,0))

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Inverse()

In [320]:
I = np.matrix([[1,2],[3,4]])
print(np.linalg.inv(I))

[[-2.   1. ]
 [ 1.5 -0.5]]


# Power()

In [326]:
I = np.matrix([[1,2],[3,4]])
print(np.linalg.matrix_power(I,2))

[[ 7 10]
 [15 22]]


# Determinate()

In [329]:
d = np.matrix([[1,2,3],[3,4,3],[1,2,3]])
print(np.linalg.det(d))

0.0


In [5]:
aar = np.array([[10.5,22.,np.nan],[41,52.5,np.nan]])

In [6]:
aar


array([[10.5, 22. ,  nan],
       [41. , 52.5,  nan]])

In [8]:
remove = aar[~np.isnan(aar)]

In [9]:
aar

array([[10.5, 22. ,  nan],
       [41. , 52.5,  nan]])

In [10]:
remove

array([10.5, 22. , 41. , 52.5])