In [2]:
import numpy as np

In [5]:
arr=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [9]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
type(arr)

numpy.ndarray

In [17]:
num_rows= np.shape(arr)[0]
print(num_rows)

3


np.power()
np.reciprocal()
np.mod()
np.ad()
np.subtract()
np.multiply()
np.divide()

Determinants, Eigen Vectors


In [8]:
arr2 = np.array([[32,45,65],[90,8,7],[10,49,90]])

In [11]:
np.divide(arr,arr2)

array([[0.03125   , 0.04444444, 0.04615385],
       [0.04444444, 0.625     , 0.85714286],
       [0.7       , 0.16326531, 0.1       ]])

In [12]:
np.power(arr,arr2)

array([[                   1,       35184372088832,  7752514261426648835],
       [                   0,               390625,               279936],
       [           282475249,                    0, -5365208890106504175]])

In [13]:
np.add(arr,arr2)

array([[33, 47, 68],
       [94, 13, 13],
       [17, 57, 99]])

In [16]:
np.reciprocal(arr)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [24]:
np.linalg.det(arr)

-9.51619735392994e-16

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.linspace(100,1000)

array([ 100.        ,  118.36734694,  136.73469388,  155.10204082,
        173.46938776,  191.83673469,  210.20408163,  228.57142857,
        246.93877551,  265.30612245,  283.67346939,  302.04081633,
        320.40816327,  338.7755102 ,  357.14285714,  375.51020408,
        393.87755102,  412.24489796,  430.6122449 ,  448.97959184,
        467.34693878,  485.71428571,  504.08163265,  522.44897959,
        540.81632653,  559.18367347,  577.55102041,  595.91836735,
        614.28571429,  632.65306122,  651.02040816,  669.3877551 ,
        687.75510204,  706.12244898,  724.48979592,  742.85714286,
        761.2244898 ,  779.59183673,  797.95918367,  816.32653061,
        834.69387755,  853.06122449,  871.42857143,  889.79591837,
        908.16326531,  926.53061224,  944.89795918,  963.26530612,
        981.63265306, 1000.        ])

In [ ]:
np.full((rows,column),number)
np.arrange(start,stop,gap)

In [37]:
np.zeros((20,20))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.